src/model_selection/mod.rs
#5 
...
* implement `test_indices`, `test_matrices`, `split` to accept a matrix and return a `Vec`
* improve allocation (?)
* make all three to return an iterator (?)
=> KFold cross-validation

src/algorithm/sort/heap_select.rs, src/neighbors/knn_regressor.rs
Hi, thanks for this cool library.
I tried to use the KNNRegressor with k = 1: 
```rust
let knn = KNNRegressor::fit(
&X,
&Y,
Distances::euclidian(),
KNNRegressorParameters {
algorithm: KNNAlgorithmName::CoverTree,
k: 1,
weight: KNNWeightFunction::Uniform,
},
)?;
```
But it failed due to https://github.com/smartcorelib/smartcore/blob/a2588f6f459b6138fb40aa2b29dd456478e5f29d/src/neighbors/knn_regressor.rs#L119
I cloned this project and changed that line and it worked fine with my dataset! 
Is there something that I can do to add that support here? I also tried to run that with LinearSearch algorithm instead of CoverTree algorithm in
```rust
let knn = KNNRegressor::fit(
&X,
&Y,
Distances::euclidian(),
KNNRegressorParameters {
algorithm: KNNAlgorithmName::LinearSearch,
k: 1,
weight: …
```
=> Allow KNN with k=1

src/lib.rs, src/linalg/mod.rs, src/linalg/naive/dense_matrix.rs, src/linalg/nalgebra_bindings.rs, src/linalg/ndarray_bindings.rs, src/math/num.rs, src/svm/mod.rs, src/svm/svr.rs
This PR covers part of #9 
Here I introduce:
* [e-SVR](https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVR.html#sklearn.svm.SVR) implementation
* 3 new methods in `linalg` module: `BaseVector::dot`, `BaseVector::approximate_eq`, `BaseMatrix::get_row`
SVR implementation lacks proper documentation but I plan to add it in a separate PR
=> epsilon-SVR + new methods in BaseMatrix and BaseVector

src/svm/mod.rs, src/svm/svc.rs
In this PR I continue to work on #9. Here I add Support Vector Classifier (SVC) implementation that closely follows algorithm described [here](https://www.jmlr.org/papers/volume6/bordes05a/bordes05a.pdf). 
SVC implementation lacks proper documentation but I plan to add it in a separate PR
=> feat: adds support vector classifier

src/linalg/mod.rs, src/linalg/naive/dense_matrix.rs, src/linalg/nalgebra_bindings.rs, src/linalg/ndarray_bindings.rs, src/svm/mod.rs, src/svm/svc.rs
Here I add additional methods to `smartcore::linalg::BaseVector` since SVM kernel function is defined for 2 vectors and we need most of these new methods to calculate kernel value. 
Also I add 3 new SVM kernels: Gaussian, Polynomial and Sigmoid. 
Finally I change SVC a bit to make sure it support various labels, not just -1 or 1. 
There is a [new example](https://github.com/smartcorelib/smartcore-examples/pull/1) that demonstrates difference between different SVM kernels.
=> Three more SVM kernels, adds more methods to BaseVector

src/error/mod.rs, src/linalg/cholesky.rs, src/linalg/mod.rs, src/linalg/naive/dense_matrix.rs, src/linalg/nalgebra_bindings.rs, src/linalg/ndarray_bindings.rs
This is the first step in implementing Ridge Regression (#20). 
In this PR I add [Cholesky decomposition routine](https://en.wikipedia.org/wiki/Cholesky_decomposition) that can be extended by any matrix that implements `BaseMatrix` trait
=> feat: adds Cholesky matrix decomposition

src/linalg/mod.rs, src/math/vector.rs, src/metrics/cluster_helpers.rs, src/naive_bayes/mod.rs
I wanted to implement a generic way to convert a Vec<T> to a BaseVector<T> but then I realized that I could do that as &[T] which fits in the &Vec<T> case.
I also changed the implementation of RealNumberVector over BaseVector instead of over Vec<T> so I can use that in the implementation of the other Naive Bayes classifiers without the need of creating a Vec<T> from the data. Everything should work at the same way. The only major concern there is that if  BaseVector  is on scope it would be necessary to call that at this way because it conflicts with the BaseVector unique function:
```rust
RealNumber::unique(v);
```
=> Add capability to convert a slice to a BaseVector

src/naive_bayes/categorical.rs, src/naive_bayes/mod.rs
Changing interface of NBDistribution to use log likelihood in order to make calculations more fast and stable
=> Use log likelihood to make calculations more stable

Cargo.toml, src/linalg/naive/dense_matrix.rs, src/linalg/nalgebra_bindings.rs, src/linalg/ndarray_bindings.rs
Changing the implementation of to_row_vector in nalgebra. It is now a reshape to (1, number of elements).
It was necessary an upgrade of the nalgebra crate in order to be able to use `reshape_generic`.
=> Change implementation of to_row_vector for nalgebra

src/algorithm/neighbour/bbd_tree.rs, src/algorithm/neighbour/cover_tree.rs, src/algorithm/neighbour/mod.rs, src/decomposition/pca.rs, src/ensemble/random_forest_classifier.rs, src/lib.rs, src/linalg/evd.rs, src/linalg/lu.rs, src/linalg/naive/dense_matrix.rs, src/linalg/qr.rs, src/linalg/stats.rs, src/linalg/svd.rs, src/linear/bg_solver.rs, src/linear/lasso.rs, src/linear/logistic_regression.rs, src/linear/ridge_regression.rs, src/math/distance/euclidian.rs, src/metrics/auc.rs, src/metrics/cluster_helpers.rs, src/model_selection/mod.rs, src/naive_bayes/bernoulli.rs, src/naive_bayes/gaussian.rs, src/naive_bayes/multinomial.rs, src/neighbors/knn_classifier.rs, src/optimization/line_search.rs, src/tree/decision_tree_classifier.rs, src/tree/decision_tree_regressor.rs
clippy::ptr_arg is still present in:
Not sure how to fix that warning in those files.
Closes #22
=> fix needless-range and clippy::ptr_arg warnings.

Cargo.toml, src/linalg/ndarray_bindings.rs
Use the last version of ndarray, a change was necessary due to a change in the API:
> The old function stack has been renamed to concatenate. A new function stack with numpy-like semantics have taken its place. Old usages of stack should change to use concatenate.
See in: https://github.com/rust-ndarray/ndarray/blob/master/RELEASES.md
=> fix: Update ndarray version

src/linalg/mod.rs, src/linalg/naive/dense_matrix.rs, src/linalg/nalgebra_bindings.rs, src/linalg/ndarray_bindings.rs, src/linear/elastic_net.rs, src/linear/elasticnet.rs, src/linear/lasso.rs, src/linear/lasso_optimizer.rs, src/linear/mod.rs
This is my final PR in a series of algorithms dedicated to linear regression regularization. 
1. This PR refactors Lasso. I've moved the Interior-Point Method for Large-Scale l1-Regularized Least Squares into a separate file. 
1. Add ElasticNet struct that adds regularization penalties to the linear regression loss function during training.
1. Change a scaling factor for l1 regularization parameter for Lasso
=> Elastic Net

src/decomposition/mod.rs, src/decomposition/pca.rs, src/decomposition/svd.rs, src/linalg/mod.rs, src/linalg/naive/dense_matrix.rs, src/linalg/nalgebra_bindings.rs, src/linalg/ndarray_bindings.rs, src/linear/elastic_net.rs, src/linear/elasticnet.rs, src/linear/lasso.rs, src/linear/lasso_optimizer.rs, src/linear/mod.rs
This PR adds a convenient struct that can be used for dimensionality reduction of a dataset. Also, it fixes some problems with an associated method, PCA
=> Singular Value Decomposition (SVD)

src/error/mod.rs
Adds `non_exhaustive` attribute to crate::error::FailedError to indicate that this type may have more fields added in the future
=> feat: makes smartcore::error:FailedError non-exhaustive

src/lib.rs
I noticed the following typo error whilst reading your 0.2.0 release notes. 
Congrats on the release BTW!
=> Fix Matrix typo in documentation

src/linear/logistic_regression.rs
This PR adds a L2 regularization term to the binary and multi-class cost function of logistic regression. 
The strength of the regularization is controlled by parameter `alpha` >= 0. When `alpha`  -> +inf value of regression coefficients -> 0 and and vice versa
=> feat: adds l2 regularization penalty to the Logistic Regression

src/lib.rs, src/linalg/mod.rs, src/linalg/stats.rs, src/linear/lasso_optimizer.rs, src/optimization/first_order/lbfgs.rs
This fixes the clippy warnings added in the new version of clippy
=> fix: Fix new clippy warnings

src/dataset/mod.rs
Right now if we run
```cargo build --target wasm32-unknown-unknown --release --all-features``` it fails with:
```bash
error[E0308]: mismatched types
--> src/dataset/mod.rs:88:49
|
88 |         let num_features = usize::from_le_bytes(buffer);
|                                                 ^^^^^^ expected an array with a fixed size of 4 elements, found one with 8 elements
error[E0308]: mismatched types
--> src/dataset/mod.rs:90:48
|
90 |         let num_samples = usize::from_le_bytes(buffer);
|                                                ^^^^^^ expected an array with a fixed size of 4 elements, found one with 8 elements
error: aborting due to 2 previous errors
```
According to the [documentation](https://doc.rust-lang.org/std/primitive.usize.html#method.from_le_bytes) from_le_bytes …
=> fix: Change to compile for wasm32-unknown-unknown target

src/dataset/generator.rs
Implemented a `make_moons` generator in response to #53. Followed the same logic as [sklearn](https://github.com/scikit-learn/scikit-learn/blob/95119c13a/sklearn/datasets/_samples_generator.py#L683) and borrowed some syntax from the `make_circles` data generator as implemented in smartcore.
=> Adding `make_moons` data generator

src/naive_bayes/bernoulli.rs, src/naive_bayes/categorical.rs, src/naive_bayes/gaussian.rs, src/naive_bayes/multinomial.rs
This is related to https://github.com/smartcorelib/smartcore/issues/73:
Things that are done in this PR
- Add a getter equivalent to the scikitlearn attributes of the GaussianNB class for classes_, class_prior_, var_, and theta_.
- Rename sigma to var, in order to have a similar naming that in scikitlearn (sigma is [deprecated](https://github.com/scikit-learn/scikit-learn/blob/8c6a045e46abe94e43a971d4f8042728addfd6a7/sklearn/naive_bayes.py#L160))
=> feat: Add getters for naive bayes structs

src/dataset/mod.rs
Fixes https://github.com/smartcorelib/smartcore/issues/87
=> fix: Use usize size for usize::from_le_bytes buffer

src/algorithm/neighbour/cover_tree.rs, src/lib.rs, src/linalg/naive/dense_matrix.rs
Fix clippy warnings added when we are building this library with the latest stable version of Rust.
=> style(lint): fix clippy warnings

src/algorithm/neighbour/cover_tree.rs
Thank you for all the work you have done on this! My friend and I have been trying to use smartcore's k-nearest neighbors algorithm as part of a dynamic label propagation implementation and we believe we have discovered an issue. The original cover tree version of the k-nearest neighbors algorithm might not work for cases where there are multiple points equidistant from the input point. For example, the current test passes for the given parameters (input point  = 5, k = 3), but fails if k is increased to 4. This is because there are 5 points in the dataset within a radius of 2.0 from 5 (3, 4, 5, 6, 7) and the algorithm does not sort them by distance from the input point before taking the first 4 points from the `neighbors` vector. This has been corrected by sorting the `neighbors` vector …
=> Fix issue with cover tree k-nearest neighbors

src/svm/svc.rs
As discussed in #134, I have tried to implement `decision_function` for SVC.
Please let me know if you have any feedback.
=> Add SVC::decision_function (#134)

src/algorithm/neighbour/bbd_tree.rs, src/linalg/evd.rs, src/optimization/mod.rs, src/svm/svr.rs, src/tree/decision_tree_classifier.rs, src/tree/decision_tree_regressor.rs
Added an additional doctest to `evd.rs` for a matrix that resulted in failure before these changes. In several locations, changed indices from `i as usize + 1` to `(i+1) as usize` to avoid overflow in type conversion. 
Fixes #140.
=> Added additional doctest and fixed indices

src/linalg/mod.rs, src/preprocessing/mod.rs, src/preprocessing/numerical.rs
In this branch I added an implementation for a `StandardScaler` as described in issue #54.
=> Implementation of Standard scaler

src/math/num.rs, src/metrics/precision.rs, src/metrics/recall.rs
This implements `micro` averaging for multiclass precision/recall to handle #151. I believe this is a good default, since it handles imbalanced labels better than `macro` averaging (which is also not yet implemented).
Additionally, the documentation for `to_f32_bits` is incorrect, and that function may currently cause unexpected behavior because it truncates half the bits for f64 values. This breaks things like the uniqueness check I'm doing to count the number of distinct labels. I'd also be open to better methods to count distinct floating point values in Rust, but I haven't seen an easy library function that handles this (with nans etc). I've added `to_f64_bits` to provide the behavior I expected.
=> Handle multiclass precision/recall

src/linear/elastic_net.rs, src/linear/lasso.rs, src/linear/linear_regression.rs, src/linear/logistic_regression.rs, src/linear/ridge_regression.rs, src/model_selection/hyper_tuning.rs, src/model_selection/mod.rs
Implements a basic grid search for #153. This approach will requires that we implement Iterator SearchParameter structs for all estimators that have Parameters<T> that can be searched.
=> grid search

src/lib.rs, src/linalg/mod.rs, src/math/num.rs, src/readers/csv.rs, src/readers/error.rs, src/readers/io_testing.rs, src/readers/mod.rs
Looking into implementing #66.
=> Implement a generic read_csv method

Cargo.toml, src/algorithm/neighbour/fastpair.rs
I got:
```rust
warning: unused import: `itertools::Itertools`
--> /Users/morenol/me/smartcore/src/algorithm/neighbour/fastpair.rs:2:5
|
2 | use itertools::Itertools;
|     ^^^^^^^^^^^^^^^^^^^^
|
= note: `#[warn(unused_imports)]` on by default
```
which is only used in force-brute implementation
=> fix: fix compilation warnings when running only with default features

Cargo.toml
rand_distr is only used in dataset module
https://github.com/smartcorelib/smartcore/blob/162bed2aa2242e35e02c875821d0d7abaf054070/src/dataset/generator.rs#L5
=> Make rand_distr optional

src/svm/svc.rs
In test output we are not getting which is the accuracy when it fails. This could help us identify what is going on. I think that it should be related to the fact that these tests depend on `rand` crate usage.
I see that sometimes the accuracy is 1.0, others, 0.95, others 0.9.
=> test: provide better output in svm::svc tests

src/cluster/kmeans.rs, src/svm/svc.rs, src/tree/decision_tree_classifier.rs, src/tree/decision_tree_regressor.rs
#164 & #166 didn't have a direct conflict, but they did race while adding both seeds and search params to certain classes. This completes them together.
=> Add seed params to search params

src/algorithm/neighbour/mod.rs, src/cluster/dbscan.rs, src/cluster/kmeans.rs, src/decomposition/pca.rs, src/decomposition/svd.rs, src/ensemble/random_forest_classifier.rs, src/ensemble/random_forest_regressor.rs, src/linear/elastic_net.rs, src/linear/lasso.rs, src/linear/linear_regression.rs, src/linear/logistic_regression.rs, src/linear/ridge_regression.rs, src/naive_bayes/bernoulli.rs, src/naive_bayes/categorical.rs, src/naive_bayes/gaussian.rs, src/naive_bayes/multinomial.rs, src/neighbors/knn_classifier.rs, src/neighbors/knn_regressor.rs, src/neighbors/mod.rs, src/svm/svc.rs, src/tree/decision_tree_classifier.rs, src/tree/decision_tree_regressor.rs
Implements #165 for all algorithms.
- SVMSearchParams & DecisionTreeSearchParams were missing the new seeds from regular params, so this completes that update as well.
=> make default params available to serde

src/ensemble/random_forest_regressor.rs, src/linalg/dense/matrix.rs, src/linear/elastic_net.rs, src/neighbors/knn_classifier.rs, src/neighbors/knn_regressor.rs, src/tree/decision_tree_regressor.rs
I think this completes the merge of development. The rest of the warnings look related to decision tree implementations which I'm less familiar with.
=> Linalg refactoring - cleanup rng merge

src/model_selection/hyper_tuning.rs, src/model_selection/hyper_tuning/grid_search.rs, src/model_selection/hyper_tuning/mod.rs, src/model_selection/mod.rs
I just saw that this mod is not being imported so it is not being used and the tests are not running.
I noticed this while reviewing https://github.com/smartcorelib/smartcore/pull/169
=> feat: expose hyper tuning module in model_selection

src/model_selection/hyper_tuning/grid_search.rs, src/model_selection/hyper_tuning/mod.rs, src/model_selection/mod.rs
A little bit of refactoring of the search_grid module to add the GridSearchCV with a similar shape to https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html#
@montanalow please let me know if this sounds good to you. I would love to have this merged before addressing https://github.com/smartcorelib/smartcore/pull/169
=> feat: Create GridSearchCV

src/svm/svc.rs
There is an issue with the iterator for SVC Search'
```rust
&& self.current_seed == self.svc_search_parameters.kernel.len()
```
should be
```rust
&& self.current_seed == self.svc_search_parameters.seed.len()
```
=> fix: fix issue with iterator for svc search

src/dataset/breast_cancer.rs, src/dataset/diabetes.rs, src/dataset/mod.rs
=> Fix compilation issues for wasm

.github/workflows/ci.yml, Cargo.toml, src/linalg/basic/matrix.rs, src/numbers/floatnum.rs, src/svm/mod.rs, src/svm/svc.rs, src/svm/svr.rs
Fixes #217 and added tests for default target to make sure that we can compile smartcore without the default features
Compiling with `--no-default-features` fails.
Compiling with `--no-default-features` works
=> build: fix compilation without default features

src/svm/mod.rs, src/svm/svc.rs, src/svm/svr.rs
Fixes #
* Remove lifetimes in Kernel trait.
* Use box instead of & for Kernel objects n SVM structs.
*
=> Use Box in SVM and remove lifetimes

.github/workflows/ci.yml, Cargo.toml, src/rand_custom.rs
=> Fixes for release
